services:
  manager:
    image: docker:dind
    privileged: true
    container_name: manager
    volumes:
      - manager-home:/home/manager

  node1:
    image: docker:dind
    privileged: true
    container_name: node1

  node2:
    image: docker:dind
    privileged: true
    container_name: node2

  node3:
    image: docker:dind
    privileged: true
    container_name: node3

volumes:
  manager-home:
