services:
  manager:
    build: .
    privileged: true
    container_name: manager
    ports:
      - "80:80"
    volumes:
      - manager-home:/home/manager

  node1:
    build: .
    privileged: true
    container_name: node1

  node2:
    build: .
    privileged: true
    container_name: node2

  node3:
    build: .
    privileged: true
    container_name: node3

volumes:
  manager-home:
