[managers]
esgi-2604-ansible-manager-1

[managers:vars]
ansible_connection=community.docker.docker

[workers]
esgi-2604-ansible-node-1
esgi-2604-ansible-node-2
esgi-2604-ansible-node-3
esgi-2604-ansible-node-4

[workers:vars]
ansible_connection=community.docker.docker



